Optutils refactor
Complete refactor of the command line parsing and structure of the code
in the swork frontend. Now uses optutils to provide a consistent and
clean way to parse arguments. Not yet stabilized

Signed-off-by: Tim Henderson <tim.tadh@gmail.com>

diff --git a/bin/swork b/bin/swork
--- a/bin/swork
+++ b/bin/swork
@@ -6,17 +6,16 @@
 #Copyright: 2011 All Rights Reserved, Licensed under the GPLv2, see LICENSE
 
 commands=$(/usr/bin/python -m swork $@)
-if (( $? > 1 )); then
-    echo "swork did not succeed, see error message and usage info."
-    return 1;
+exitcode=$?
+
+if (( $exitcode != 0 && $exitcode != 1 && $exitcode != 126 )); then
+    echo "swork failed, see error and usage info";
+elif (( $exitcode == 0 )); then
+    IFS=$'\n'
+    for cmd in $commands
+    do
+        eval $cmd;
+    done
+    unset IFS
 fi
 
-IFS=$'\n'
-for cmd in $commands
-do
-#     echo $cmd;
-    eval $cmd;
-done
-unset IFS
-
-# echo "... now start your work!"
